dataset_name: Peptides-struct
model_type: gnn_vn
local_gnn_type: gated_gcn
use_full_graph: False
atom_dim: 64
bond_dim: 64
ckpt_pos_encoder_path: "/cm/shared/khangnn4/WavePE/ckpts/PCBA_debug_1/PCBA_epoch=99_train_loss=0.010_val_loss=0.011_val_best_loss=0.011.ckpt"
num_layer: 3
num_heads: 4
device: cuda:6
out_dim: 11
pos_dim: 20
num_epoch: 100
batch_size: 32
val_batch_size: 32
mpnn_type: gated
lr: 5e-4 ### func 
#lr: 5e-3
dropout: 0.0
graph_pooling: mean
attn_dropout: 0.5
weight_decay: 1e-4 ### for peptides struct
scale: False
concat: False
freeze: True
scheduler: cosine_with_warmup
learnable: True
warmup_steps: 20
optimizer: adam
clip_grad_norm: False