dataset_name: ogbg-molbace
model_type: 
local_gnn_type: 
use_full_graph: False
atom_dim: 300
bond_dim: 300

ckpt_pos_encoder_path: "/cm/shared/khangnn4/WavePE/ckpts/PCBA_debug_1/PCBA_epoch=99_train_loss=0.010_val_loss=0.011_val_best_loss=0.011.ckpt"

num_layer: 5
num_heads: 4
device: cuda ##2
out_dim: 1
pos_dim: 20
num_epoch: 100
batch_size: 32
val_batch_size: 32
mpnn_type: gated
lr: 1e-3 ### func 
#lr: 5e-3
dropout: 0.5
graph_pooling: add
attn_dropout: 0.5
weight_decay: 1e-9 ### for peptides struct
clip_grad_norm: False
scheduler: cosine_with_warmup

learnable: True
residual: False
warmup_steps: 20
optimizer: adam
use_norm: True
affine: True
scale: True
concat: False
freeze: True