dataset_name: zinc
model_type: GT
use_full_graph: False
atom_dim: 64
bond_dim: 84
#ckpt_pos_encoder_path: /cm/shared/khangnn4/WavePE/ckpts/PCBA_2/PCBA_epoch=49_train_loss=0.087_val_loss=0.090_val_best_loss=0.090.ckpt
#ckpt_pos_encoder_path: /cm/shared/khangnn4/WavePE/ckpts/PCBA_2/PCBA_epoch=49_train_loss=0.087_val_loss=0.090_val_best_loss=0.090.ckpt
ckpt_pos_encoder_path: /cm/shared/khangnn4/WavePE/ckpts/PCBA_small_resolution/PCBA_epoch=77_train_loss=0.267_val_loss=0.277_val_best_loss=0.277.ckpt
num_layer: 8
num_heads: 4
device: cuda:2
out_dim: 1
pos_dim: 20
num_epoch: 2000
batch_size: 128
mpnn_type: gated
lr: 1e-3 ### func 
#lr: 5e-3
dropout: 0.0
graph_pooling: sum
attn_dropout: 0.5
weight_decay: 1e-9 ### for peptides struct
local_gnn_type: GINE
global_model_type: Transformer
batch_norm: True
layer_norm: False

scheduler: reduce_on_plateau
warmup_steps: 50
clip_grad_norm: True
batch_size: 128
val_batch_size: 16
learnable: True
optimizer: adam
use_norm: True
affine: True
scale: True
residual: True
